### ISSUE TITLE
Zugriff nicht erlaubt

### ISSUE THREAD

**Issue by creditfairedv** [europace/authorization-api#2]
Ich kann machen was ich will, es kommt immer „Forbidden“ raus. Um die Programmierung auszuschließen habe ich es auch über curl probiert, mit dem selben Ergebnis. Eventuell liegt es am Endpunkt. In der yaml-Datei steht als Endpunkt „http://ep-authorization-service.services.ps.rz-hypoport.local“. Den gibt es aber für mich nicht. Mit dem alternativen Endpunkt „https://api.europace.de/access-token“ oder „https://api.europace.de/“ bekomme ich „Forbidden“.

**Comment by ollio** [comment]
Die Adressen der Authorization Server lauten:
https://api.europace.de/.well-known/oauth-authorization-server oder
https://api.europace2.de/.well-known/oauth-authorization-server

Mit welcher ClientID melden Sie sich an und unter welcher PartnerId ist der Client registriert?

**Comment by creditfairedv** [comment]
Die PartnerId ist SRR90.
Die ClientId ist MQIESMPVUNMLGXLB.

**Comment by creditfairedv** [comment]
OK, jetzt geht es. Oben angegebene Adressen geben einem dann den "richtigen" Endpoint zurück.

**Comment by creditfairedv** [comment]
Leider geht es inzwischen nicht mehr. Ich bekomme nun:
{"error_description":"Unexpected server error","error":"server_error"}

Die Anfrage ist die selbe die vorher einen Access-Token zurückgeliefert hat.

**Comment by ollio** [comment]
Wir sind da stetig am entwickeln um Produktionsreife zu erlangen. Danke für den Hinweis. wir gehen dem nach.

**Comment by caspii** [comment]
@creditfairedv klappt es jetzt wieder?

**Comment by creditfairedv** [comment]
Leider nein.

**Comment by caspii** [comment]
@creditfairedv Jetzt sollte es wieder klappen

**Comment by caspii** [comment]
@creditfairedv hast du Slack?

**Comment by creditfairedv** [comment]
Nein, Slack habe ich leider nicht.

Das Problem besteht auch weiter. Noch eine Ergänzung von mir: als Endpoint hatte ich aus den oben genannten, folgenden herausfinden können: https://api.europace.de/auth/access-token"

**Comment by creditfairedv** [comment]
Habe gerade gesehen das sich der Endpoint geändert hat auf https://api.europace.de/auth/token. Bringt leider aber auch kein anderes Ergebnis.

**Comment by gruenewa** [comment]
Ich habe gerade den Endpoint mit Curl abgerufen und dabei eine Access-Token erhalten. Mein Aufruf war:

**Comment by creditfairedv** [comment]
OK, jetzt geht es. Danke.

**Comment by caspii** [comment]
Super. Dann schließen wir dieses Issue. Falls es ein neues Problem gibt, bitte neues Issue aufmachen.
