### ISSUE TITLE
SSO / Client-Approval Link führt auf 404er

### ISSUE THREAD

**Issue by ic-hv** [europace/authorization-api#23]
Da ich mich gerade damit befasse, inwiefern sich der SSO-Mechanismus https://github.com/europace/login-api#silent-sign-on (Sonderfall: einloggen mit einer untergeordneten Partner ID) mittels dem "client credential" - OAuth2-Flow durchführen lässt, bin ich im README.md für die neue authorization-api  (in der meiner Meinung nach für mich relevanten Sektion) über einen nicht funktionsfähigen Link gestolpert: https://github.com/europace/authorization-api/blob/master/Client-Approval.md#client-approval

**Comment by ic-hv** [comment]
Im wesentlichen suche ich nach einer Beschreibung wie man im Kontext der neuen "client credential" Authentifizierung eine untergeordnete Partner ID via SSO bei Europace anmelden und auf eine URL weiterleiten kann. Momentan nutze ich nämlich noch den folgenden (deprecated) Mechanismus): https://github.com/europace/login-api/blob/83b4f647f34aa456d83b088dec7d8d4970ae5e93/SSO-DEPRECATED.md

**Comment by caspii** [comment]
Hi, entschuldige die verspätete Anwort. 
Es liegt nun eine neue Dokumentation inklusive Migrations-Strategie hier vor: https://docs.api.europace.de/baufinanzierung/authentifizierung/

**Comment by ic-hv** [comment]
Nun ja, also meine eigentlichen Fragen wurden durch den von Dir genannten Link ja nun nicht beantwortet: 

Also nochmal kurz zusammengfasst:

Wann ist meiner Umsetzug der SSO via OpenConnectID zur rechnen und wird das von mir im ersten Post verlinkte Verfahren noch unterstützt werden bis es soweit ist - anderfalls hätte unser Kunde nämlich ein Problem!

**Comment by caspii** [comment]
1. Das neue SSO Verfahren mit OpenIDcConnect ist aktuell in der Entwicklung, wird vermutlich innerhalb der nächsten 4* Wochen fertig werden. Danach wird es möglich sein, einen externen IdP an Europace anzuschliessen. Nutzer melden sich an diesem IdP an und werden zu Europace weitergeleitet. Es handelt sich hierbei *nicht* um einen "Silent Sign On" = darunter verstehen wir, dass ein Nutzer reibungslos (ohne Login-Maske) von einer Plattform zu Europace wechselt.
2. Das Verfahren wird weiterhin unterstützt. Es gibt aktuell keine Pläne es abzuschalten.

---
* Alle Angaben ohne Gewähr
