### ISSUE TITLE
Verbesserung des authorization.yaml

### ISSUE THREAD

**Issue by a-dudko** [europace/authorization-api#26]
Vielleicht könnte authorization.yaml verbessert werden:

- info.version ist "0.1". Ist das korrekt?
- Der Response-Teil enthält schema.type: object. Wäre es vielleicht möglich, eine Klasse in "schemas" zu beschreiben? Derzeit wird die generierte Klasse vom swagger-codegen "InlineResponse200" genannt.
- Sollte "expires_in" vom Typ integer sein?

**Comment by MikeKrueger75** [comment]
Hi, 
thanks for giving us feedback. We improve the open API specification as you mentioned.
