### ISSUE TITLE
Auth Code Flow: Unauthorized client: Scope `impersonieren` is required if subject != actor

### ISSUE THREAD

**Issue by dneukirchen** [europace/authorization-api#72]
Wir haben folgendes Problem beim auth code flow: 

Nachdem wir den code erhalten und ihn gegen ein access + id token austauschen wollen, erhalten wir die 400er fehlermeldung:

```
{
    "error_description": "Unauthorized client: Scope `impersonieren` is required if subject != actor",
    "error": "unauthorized_client"
}
```

unser request:

```
POST /auth/token HTTP/1.1
Host: api.europace.de
Authorization: Basic [CLIENT_CREDENTIALS]
Content-Type: application/x-www-form-urlencoded
grant_type=authorization_code&code=[CODE]&redirect_uri=[REDIRECT_URI]
```

unser client hat den erforderlichen scope "openid" (laut docs sind keine weiteren scopes erforderlich)

Nach unserem Verständnis der Doku sollte die hier greifende Validierung (actor !== subject) nur für den grant_type="client_credentials" Anwendung finden. 

Viele Grüße aus der Domstadt,
David

**Comment by dneukirchen** [comment]
Update:

es liegt am encoding des scope parameters im vorhergehenden authorize requests (`https://www.europace2.de/authorize/?response_type=code&scope=xxx`)

Wird die Kodierung gemäß [RFC1738](http://www.faqs.org/rfcs/rfc1738) und dem application/x-www-form-urlencoded-Medientyp durchgeführt (was bedeutet, dass Leerzeichen als Pluszeichen kodiert werden), kommt es beim darauffolgenden code exchange request zu obigem 400er Fehler. Die scopes werden zwar auf der authorize Seite dem User korrekt angezeigt, aber der nach dem approval erzeugte code kann nicht eingetauscht werden.

Wir haben das nun unsererseits gefixed, indem wir die parameter gemäß [RFC3986](http://www.faqs.org/rfcs/rfc3986) kodieren (Leerzeichen werden mit einem Prozentzeichen (%20) kodiert). 

ping und danke an @MikeKrueger75

**Comment by dneukirchen** [comment]
Update: 

Nach einigen tests ist uns aufgefallen, dass es sich hierbei nicht um ein encoding issue handelt, sondern einige scopes nicht registrierbar sind, da es vermutlich Berechtigungsprobleme beim dem Benutzer und oder Client gibt.

Dazu zählen in unserem Fall: baufinanzierung:echtgeschaeft und alle privatkredit:* scopes.

Wenn wir mit einem neuen Benutzer autorisieren und mindestens einen dieser Scopes mitschicken, bekommen wir den oben geschilderten Fehler. **In diesem fall ist also keine Autorisierung möglich, da der access token request scheitert.**

Wenn wir allerdings zunächst mit anderen, konfliktfreien scopes (bspw. 'baufinanzierung:vorgang:lesen') autorisieren funktioniert es und wir bekommen auch bei zukünftigen Durchläufen mit den oben genannte scopes einen code zurück.

Die Scopes des tokens werden allerdings dabei nicht erweitert. In der Response des token request sind obige 5 scopes nicht enthalten, ohne dass es einen erkennbaren Fehler gibt. 

Reproduktion:

* Client an Organisationseinheit erstellen, die keinen Zugriff auf kreditsmart und/oder Echtgeschäfte hat.
* Neue Organisationseinheit mit Login unterhalb dieser Einheit anlegen.
* Auth flow mit dieser Einheit durchführen

**Comment by MikeKrueger75** [comment]
Hi David, 

danke für die ausführliche Untersuchung des Problems. 

Die Ursache sind die fehlenden Rechte für Privatkredit und Echtgeschäft. Allerdings sollte dieser Umstand nicht zu Fehlern führen. Vielmehr ist ein Access-Token mit geringeren Rechten (Scope) zu liefern, der überprüfbar ist. Anscheinend haben wir hier noch ein Issue, dass wir uns nächste Woche ansehen werden.

**Comment by MikeKrueger75** [comment]
Wir haben die Ursache gefunden und gefixt. Man bestätigt nun ausschließlich den Scope, der durch eigenen Berechtigungen in Europace möglich ist. Fehlende Berechtigungen führen nicht mehr zu der o.g. Fehlermeldung.

Closed.
